version: '3.8'

services:
    # backend API
    smart-brain-api: 
        container_name: backend
        build: ./
        command: npm start
        working_dir: /usr/src/smart-brain-api
        environment: 
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'YourPassword'
            POSTGRES_DB: smart-brain-docker
            POSTGRES_HOST: postgres
            REDIS_URI: redis://redis:6379
        ports: 
            - "3000:3000"
        volumes:
            - ./:/usr/src/smart-brain-api
    # postgres
    postgres:
        environment:
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'YourPassword'
            POSTGRES_DB: smart-brain-docker
            POSTGRES_HOST: postgres
        build: ./postgres
        ports:
            - "5432:5432"
    #redis
    redis:
        image: redis
        ports:
            - "6379:6379"